### ISSUE TITLE
Module build fails when transpiling with babel

### ISSUE THREAD

**Issue by 1337LutZ** [accessible-ui/tabs#4]
Hey guys,

I've found an issue when compiling the dist to a ES5 version:
`ERROR in ./node_modules/@accessible/tabs/dist/es/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /node_modules/@accessible/tabs/dist/es/index.js: Unexpected token, expected ";" (306:9)`

The line in question is this one: `!manualActivation && activate()` when I manually change it to: `;!manualActivation && activate()` it works. The same code error is in the cjs dist.

Is there a way to get this fixed so babel doesn't fail? Currently im stuck on this and the project wont build.

**Comment by jaredLunde** [comment]
Fixed in 1.1.1

Thanks for the report!
